<Project>
  <PropertyGroup>
    <AVPRClientPackageVersion Condition="'$(AVPRClientPackageVersion)' == ''">[0.3.0-preview.2]</AVPRClientPackageVersion>
    <AVPRClientInteropPackageVersion Condition="'$(AVPRClientInteropPackageVersion)' == ''">[0.1.0-preview.2]</AVPRClientInteropPackageVersion>
    <ValidationPackageModelPackageVersion Condition="'$(ValidationPackageModelPackageVersion)' == ''">[0.1.0-preview.2]</ValidationPackageModelPackageVersion>
    <ValidationPackageCodecsPackageVersion Condition="'$(ValidationPackageCodecsPackageVersion)' == ''">[0.1.0-preview.2]</ValidationPackageCodecsPackageVersion>
  </PropertyGroup>
</Project>
