<Project>
  <PropertyGroup>
    <ARCExpectPackageVersion Condition="'$(ARCExpectPackageVersion)' == ''">7.0.0-preview.3</ARCExpectPackageVersion>
    <AVPRClientPackageVersion Condition="'$(AVPRClientPackageVersion)' == ''">[0.3.0-preview.3]</AVPRClientPackageVersion>
    <AVPRClientInteropPackageVersion Condition="'$(AVPRClientInteropPackageVersion)' == ''">[0.1.0-preview.3]</AVPRClientInteropPackageVersion>
    <ValidationPackageModelPackageVersion Condition="'$(ValidationPackageModelPackageVersion)' == ''">[0.1.0-preview.3]</ValidationPackageModelPackageVersion>
    <ValidationPackageCodecsPackageVersion Condition="'$(ValidationPackageCodecsPackageVersion)' == ''">[0.1.0-preview.3]</ValidationPackageCodecsPackageVersion>
  </PropertyGroup>
</Project>
