<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ExpectoExtensions.fs" />
    <Compile Include="ARCValidationPackage.fs" />
    <Compile Include="ValidationSummary.fs" />
    <Compile Include="BadgeCreation.fs" />
    <Compile Include="TopLevelAPI.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AnyBadge.NET" Version="[2.0.0]" />
    <PackageReference Include="FSharp.SystemTextJson" Version="[1.4.36]" />
    <PackageReference Include="FSharpAux" Version="[2.0.0]" />
    <PackageReference Include="Expecto" Version="[10.2.3]" />
    <PackageReference Include="AVPRIndex" Version="[0.4.0]" />
  </ItemGroup>
  
</Project>
