namespace ARCExpect

open ControlledVocabulary


/// TODO: MOve to the right place!!!
module StaticCvTerms = 

    // Autogenerated
    module IsaTerms =
        module Investigation =
            module Contacts =
                let key =  CvTerm.create("INVMSO:00000023","Investigation Person First Name","INVMSO")
                let ``Investigation Person First Name`` = CvTerm.create("INVMSO:00000023","Investigation Person First Name","INVMSO")
                let ``Investigation Person Email`` = CvTerm.create("INVMSO:00000025","Investigation Person Email","INVMSO")        



    module IoTerms =
        let File      = CvTerm.create("IO:00000001","File","IO")
        let Directory = CvTerm.create("IO:00000002","Directory","IO")
        let FileType  = CvTerm.create("IO:00000003","FileType","IO")
        let Extension = CvTerm.create("IO:00000004","Extension","IO")
        /// The name of the file.
        let FileName      = CvTerm.create("IO:00000005","FileName","IO")
        let DirecotyName  = CvTerm.create("IO:00000006","DirecotyName","IO")
    
        /// The full path of the directory or file.
        let FullName     = CvTerm.create("IO:00000008","FullName","IO")
        /// The full path, relative path or a Universal Naming Convention (UNC) path
        let Path          = CvTerm.create("IO:00000009","Path","IO")
        let FilePath      = CvTerm.create("IO:00000010","FilePath","IO")
        let DirectoryPath = CvTerm.create("IO:00000c011","DirectoryPath","IO")